miss/config/routes.rb
Rails.application.routes.draw do
  get 'index_kno/index'
  get 'index_kno/result'

  root 'home#top'
  
  get 'index_inc/incidents'
  get 'index_inc/new'
  get 'index_inc/result'
  
  get 'home/top'
  
  get '/index', to: 'home#index'
  
  get '/search', to: 'home#search'
  # get '/searchsecond', to: 'home#searchsecond'
  
  get 'home/admin'
  
  get 'importcsv/new'
  post 'importcsv/create_big'
  
  post 'importcsv/create_middle'
  
  post 'importcsv/create_small'
  
  # post 'importcsv/create_gyomu'
  
  post 'importcsv/create_small_security'
  
  post 'importcsv/create_security'
  
  ## 追加部分
  post 'importcsv/create_incident_security'
  
  post 'importcsv/create_incident'
  
  ## 追加部分2
  post 'importcsv/create_category'
  
  ## 追加部分2
  post 'importcsv/create_sakuin'
  post 'importcsv/create_knowledge'
  
  ## 追加部分3
  post 'importcsv/create_incident_category'
  
  ## 追加部分3
  post 'importcsv/create_incident_knowledge'
  
  delete 'importcsv/delete_and_reset_big'
  delete 'importcsv/delete_and_reset_middle'
  delete 'importcsv/delete_and_reset_small'
  # delete 'importcsv/delete_and_reset_gyomu'
  delete 'importcsv/delete_and_reset_small_security'
  delete 'importcsv/delete_and_reset_security'
  
  ## 追加部分
  delete 'importcsv/delete_and_reset_incident_security'
  delete 'importcsv/delete_and_reset_incident'
  
  ## 追加部分2
  delete 'importcsv/delete_and_reset_category'
  
  ## 追加部分2
  delete 'importcsv/delete_and_reset_sakuin'
  delete 'importcsv/delete_and_reset_knowledge'
  
  ## 追加部分3
  delete 'importcsv/delete_and_reset_incident_category'
  
  ## 追加部分3
  delete 'importcsv/delete_and_reset_incident_knowledge'

  ## For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

miss/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

miss/app/models/big.rb
class Big < ApplicationRecord
    has_many :middles
end

miss/app/models/category.rb
## 新規追加ファイル
class Category < ApplicationRecord
    has_many :incident_categories
    has_many :incidents, through: :incident_categories
end

miss/app/models/gyomu.rb
class Gyomu < ApplicationRecord
  belongs_to :small
  has_many :gyomu_securities
  has_many :securities, through: :gyomu_securities
end

miss/app/models/incident.bkup.rb
## 新規追加ファイル
class Incident < ApplicationRecord
    has_many :incident_securities
    has_many :securities, through: :incident_securities
end

miss/app/models/incident.rb
## 新規追加ファイル
class Incident < ApplicationRecord
    has_many :incident_categories
    has_many :categories, through: :incident_categories
    has_many :incident_securities
    has_many :securities, through: :incident_securities
    has_many :incident_knowledges
    has_many :knowledges, through: :incident_knowledges
end

miss/app/models/incident_category.rb
class IncidentCategory < ApplicationRecord
    belongs_to :incident
    belongs_to :category
end

miss/app/models/incident_knowledge.rb
class IncidentKnowledge < ApplicationRecord
    belongs_to :incident
    belongs_to :knowledge
end

miss/app/models/incident_security.rb
## 新規追加ファイル
class IncidentSecurity < ApplicationRecord
  belongs_to :incident
  belongs_to :security
end

miss/app/models/knowledge.rb
class Knowledge < ApplicationRecord
    belongs_to :sakuin
    has_many :incident_knowledges
    has_many :incidents, through: :incident_knowledges
end

miss/app/models/middle.rb
class Middle < ApplicationRecord
  belongs_to :big
  has_many :smalls
end

miss/app/models/sakuin.rb
class Sakuin < ApplicationRecord
    has_many :knowledges
end

miss/app/models/security.bkup.rb
class Security < ApplicationRecord
    has_many :small_securities
    has_many :smalls, through: :small_securities
end

miss/app/models/security.rb
class Security < ApplicationRecord
    has_many :small_securities
    has_many :smalls, through: :small_securities
## 追加箇所
##  belongs_to :small, through: :small_securities
    has_many :incident_securities
    has_many :incidents, through: :incident_securities
end

miss/app/models/small.rb
class Small < ApplicationRecord
  belongs_to :middle
  has_many :small_securities
  has_many :securities, through: :small_securities
end

miss/app/models/small_security.rb
class SmallSecurity < ApplicationRecord
  belongs_to :small
  belongs_to :security
end

miss/app/controllers/index_inc_controller.rb
class IndexIncController < ApplicationController
  def incidents
    # DBからすべての「Big」レコードを取得し、それと紐づく「Middles」「Smalls」を取得
    ## @bigs = Big.all.includes(middles: :smalls)
    ## DBからすべての「Category」レコードを取得し、それと紐づく「Incident」を取得
    @categories = Category.all.includes(:incidents)
    ## @categories = Category.all
  end
  
  def result
    # 「incident_ids」に指定されたIDに一致する「incidents」レコードをDBから取得
    @incidents = Incident.includes(:securities).where(id: params[:incident_ids])
    ##「security_ids」に指定されたIDに一致する「Securities」レコードをDBから取得
    ## @securities = Security.includes(:incidents)
  end
  
  def new
  end
  
end

miss/app/helpers/home_helper.rb
module HomeHelper
end

miss/app/helpers/importcsv_helper.rb
module ImportcsvHelper
end

miss/app/helpers/index_inc_helper.rb
module IndexIncHelper
end

miss/app/helpers/index_kno_helper.rb
module IndexKnoHelper
end

miss/app/helpers/search_helper.rb
module SearchHelper
end

miss/app/views/index_inc/incidents.html.erb
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.83.1">
  <title>Sidebars · Bootstrap v5.0</title>

  <link rel="canonical" href="https://getbootstrap.jp/docs/5.0/examples/sidebars/">

  <!-- Bootstrap core CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <!-- Favicons -->
  <link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
  <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
  <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
  <link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
  <link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
  <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
  <meta name="theme-color" content="#7952b3">
  
  <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
  </style>

    
  <!-- Custom styles for this template -->
  <link href="sidebars.css" rel="stylesheet">
</head>

<div class="title-box">
  <div style="text-align:center", class='font_test'>
    <h1><p class="moji-color"><b>PlusSEC</b></p></h1>
  </div>
</div>

<div style="text-align:right">
  <p>※ブラウザの「戻る」「進む」ボタンを押さないでください</p>
</div>

<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                    <span class="fs-5 d-none d-sm-inline">Menu</span>
                </a>
                <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                    <li>
                        <a href="/index" class="nav-link px-0 align-middle">
                            <i class="fs-4 bi-speedometer2"></i> <span class="ms-1 d-none d-sm-inline">業務から検索</span> </a>
                    </li>
                    <li>
                        <a href="/index_inc/incidents" class="nav-link px-0 align-middle">
                            <i class="fs-4 bi-table"></i> <span class="ms-1 d-none d-sm-inline">事故事例から検索</span></a>
                    </li>
                    <li>
                        <a href="/index_kno/index" class="nav-link px-0 align-middle">
                            <i class="fs-4 bi-table"></i> <span class="ms-1 d-none d-sm-inline">セキュリティ知識</span></a>
                    </li>
                    
                    <li class="nav-item">
                        <!-- /home/topへ -->
                        <a href="/home/top" class="nav-link align-middle px-0">
                            <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">ホームへ</span>
                        </a>
                    </li>
                    
                    <!-- 参考で残してる -->
                    <!--
                    <li>
                        <a href="#submenu3" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                            <i class="fs-4 bi-grid"></i> <span class="ms-1 d-none d-sm-inline">参考</span> </a>
                            <ul class="collapse nav flex-column ms-1" id="submenu3" data-bs-parent="#menu">
                            <li class="w-100">
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">参考</span> 1</a>
                            </li>
                            <li>
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">参考</span> 2</a>
                            </li>
                        </ul>
                    </li>
                    -->
                    
                </ul>
                <hr>
            </div>
        </div>
        <div class="col py-3">
            <div class="container">
              <!--resultに飛ばす-->
              <%= form_tag(index_inc_result_path, method: "get") do %>
              <!--Categoryをループで繰り返し表示-->
              <% @categories.each do |category| %>
                <div class="p-2 flex-grow-1 bd-highlight">
                <div class="category">
                  <h2><%= category.memo %></h2>
                  <% category.incidents.each do |incident| %>
                    <div class="incident" >
                      <h6>
                        <label>
                        <%= check_box_tag 'incident_ids[]', incident.id %>
                        <%= incident.summary %>
                        </label>
                      </h6>
                    </div>
                  <% end %>
                </div>
                </div>
              <% end %>
              <!--<%= submit_tag('事故事例検索', class: 'btn btn-outline-primary') %>-->
              <%= submit_tag('検索', class: 'btn-outline-primary fixed_btn') %>
              
              <% end %>
              </br>
              </br>
              </br>
              
              </div>
        </div>
    </div>
  </div>

<script>
document.addEventListener('DOMContentLoaded', function() {
  // フォーム要素を取得
  const form = document.getElementById('search-form');
  // チェックボックス要素を取得
  const checkboxes = form.querySelectorAll('input[type=checkbox]');
  // hidden要素を生成
  const hiddenInput = document.createElement('input');
  // hidden要素のタイプを指定
  hiddenInput.type = 'hidden';
  // hidden要素のname属性を指定
  hiddenInput.name = 'incident_ids';
  // hidden要素をフォームに追加
  form.appendChild(hiddenInput);
  
  // フォームの送信時に実行する処理
  form.addEventListener('submit', function(event) {
    // チェックが入っているcheckbox要素のみを選択
    const selectedCheckboxes = Array.from(checkboxes).filter(checkbox => checkbox.checked);
    // 選択されたcheckbox要素のvalueを抽出して配列にする
    const selectedIds = selectedCheckboxes.map(checkbox => checkbox.value);
    // hidden要素のvalueに選択されたcheckbox要素のvalueをカンマ区切りで格納する
    hiddenInput.value = selectedIds.join(',');
  });
});
</script>


<script>
   function toggleGroup(incId) {
      var selectAllCheckbox = document.getElementById(incId + '-selectAll');
      var checked = 0;
      var boxCount = selectAllCheckbox.length;

      for (var i = 0; i < selectAllCheckbox.length; i++) {
        if (selectAllCheckbox[i].checked) {
          checked++;
        }
      }

      if (checked === boxCount) {
        $(selectAllCheckbox).prop('checked', true);
      } else {
        $(selectAllCheckbox).prop('checked', false);
      }
    }
</script>

miss/app/views/index_inc/new.html.erb
<h1>IndexInc#new</h1>
<p>Find me in app/views/index_inc/new.html.erb</p>

miss/app/views/index_inc/result.html.erb
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.83.1">
  <title>Sidebars · Bootstrap v5.0</title>

  <link rel="canonical" href="https://getbootstrap.jp/docs/5.0/examples/sidebars/">

  <!-- Bootstrap core CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <!-- Favicons -->
  <link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
  <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
  <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
  <link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
  <link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
  <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
  <meta name="theme-color" content="#7952b3">
  
  <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
  </style>

    
  <!-- Custom styles for this template -->
  <link href="sidebars.css" rel="stylesheet">
</head>

<div class="title-box">
  <div style="text-align:center", class='font_test'>
    <h1><p class="moji-color"><b>PlusSEC</b></p></h1>
  </div>
</div>

<div style="text-align:right">
  <p>※ブラウザの「戻る」「進む」ボタンを押さないでください</p>
</div>

<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                    <span class="fs-5 d-none d-sm-inline">Menu</span>
                </a>
                <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                    <li>
                        <a href="/index" class="nav-link px-0 align-middle">
                            <i class="fs-4 bi-speedometer2"></i> <span class="ms-1 d-none d-sm-inline">業務から検索</span> </a>
                    </li>
                    <li>
                        <a href="/index_inc/incidents" class="nav-link px-0 align-middle">
                            <i class="fs-4 bi-table"></i> <span class="ms-1 d-none d-sm-inline">事故事例から検索</span></a>
                    </li>
                    <li>
                        <a href="/index_kno/index" class="nav-link px-0 align-middle">
                            <i class="fs-4 bi-table"></i> <span class="ms-1 d-none d-sm-inline">セキュリティ知識</span></a>
                    </li>
                    
                    <li class="nav-item">
                        <!-- /home/topへ -->
                        <a href="/home/top" class="nav-link align-middle px-0">
                            <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">ホームへ</span>
                        </a>
                    </li>
                    
                    <!-- 参考で残してる -->
                    <!--
                    <li>
                        <a href="#submenu3" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                            <i class="fs-4 bi-grid"></i> <span class="ms-1 d-none d-sm-inline">参考</span> </a>
                            <ul class="collapse nav flex-column ms-1" id="submenu3" data-bs-parent="#menu">
                            <li class="w-100">
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">参考</span> 1</a>
                            </li>
                            <li>
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">参考</span> 2</a>
                            </li>
                        </ul>
                    </li>
                    -->
                    
                    
                    <li>
                        <a href="/index_inc/incidents" class="nav-link px-0 align-middle">
                            <i class="fs-4 bi-table"></i> <span class="ms-1 d-none d-sm-inline">戻る</span></a>
                    </li>
                    
                </ul>
                <hr>
            </div>
        </div>
        <div class="col py-3">
            <div class="container">
                <!--index_kno_resultページに飛ばす-->
                <%= form_tag(index_kno_result_path, method: "get") do %>
                <!--@incidents（incidentsページで「incident_ids」に指定されたIDに一致するincidentテーブルのすべてのデータ）を順に取り出して繰り返し処理をする-->
                <% @incidents.each do |incident| %>

                    <h4>選択した事故事例</h4>
                    <div class="card flex-md-row mb-4 border-primary mb-3 col-lg-12">
                    <!-- テーブルsmall内のmemoカラムの内容を表示 -->
                            <h4><%= incident.summary %></h4>
                    </div>

                    <div class="row">
                        
                        <div class="col-lg-6">
                            <div class="col-xs-4">
                                <h6>事故概要</h6>
                                <div class="card flex-md-row mb-4 border-primary mb-3 h-md-250">
                                    <div class="card-body d-flex flex-column align-items-start ">
                                        <%= incident.summary %>
                                    </div>
                        　   　　 </div>
                            </div>
    
                            <div class="col-xs-4">
                            <h6>事故詳細</h6>
                            <div class="card flex-md-row mb-4 border-primary mb-3 h-md-250">
                                <div class="card-body d-flex flex-column align-items-start ">
                                    <b>原因</b><%= incident.cause %>
                                    <b>影響</b><%= incident.effect %>
                                    <b>対策</b><%= incident.taisaku %>
                                    </div>
                                </div>
                            </div>
                        </div>
                            
                        <div class="col-lg-6">
                            <div class="col-xs-4">
                                <h6>考慮するべきセキュリティ事項</h6>
                                <div class="card flex-md-row mb-4 border-primary mb-3 h-md-250">
                                        <div class="card-body d-flex flex-column align-items-start ">
                                            <!-- テーブルsecurityの関連するデータを取り出して繰り返し処理をする -->
                                            <% incident.securities.each do |security| %>
                                            <!-- テーブルsecurity内のmemoカラムの内容を表示 -->
                                            <p><b>■ <%= security.memo %></b></p>
                                            <% end %>
                                        </div>
                            　   　　 </div>
                            </div>
                                
                            <!--index_kno_resultページに飛ばす-->
                            <div class="col-xs-4">
                                <h6>単語</h6>
                                <div class="card flex-md-row mb-4 border-primary mb-3 h-md-250">
                                        <div class="card-body d-flex flex-column align-items-start ">
                                            <% incident.knowledges.each do |knowledge| %>
                                                <!-- テーブルsecurity内のmemoカラムの内容を表示 -->
                                                <label>
                                                    <%= check_box_tag 'knowledge_ids[]', knowledge.id %>
                                                    <b><%= knowledge.word %></b>
                                                </label>
                                            <% end %>
                                        </div>
                            　   　  </div>
                            </div>
                        </div>
                    </div>
                    
                    <h4>関連するURL</h4>
                    <div class="card flex-md-row mb-4 border-primary mb-3 col-lg-12">
                        <a href=<%= incident.url %>><%= incident.url %></a>
                    </div>
                    
                    <hr>
                    <!-- <hr class="bar1" > -->
                    
                <% end %>
                
                <%= submit_tag('単語の検索', class: 'btn-outline-primary fixed_btn') %>
                <% end %>
            </div>
        </div>
    </div>
</div>


<!-- scriptゾーン -->
<script>
document.addEventListener('DOMContentLoaded', function() {
  // フォーム要素を取得
  const form = document.getElementById('search-form');
  // チェックボックス要素を取得
  const checkboxes = form.querySelectorAll('input[type=checkbox]');
  // hidden要素を生成
  const hiddenInput = document.createElement('input');
  // hidden要素のタイプを指定
  hiddenInput.type = 'hidden';
  // hidden要素のname属性を指定
  hiddenInput.name = 'knowledge_ids';
  // hidden要素をフォームに追加
  form.appendChild(hiddenInput);
  
  // フォームの送信時に実行する処理
  form.addEventListener('submit', function(event) {
    // チェックが入っているcheckbox要素のみを選択
    const selectedCheckboxes = Array.from(checkboxes).filter(checkbox => checkbox.checked);
    // 選択されたcheckbox要素のvalueを抽出して配列にする
    const selectedIds = selectedCheckboxes.map(checkbox => checkbox.value);
    // hidden要素のvalueに選択されたcheckbox要素のvalueをカンマ区切りで格納する
    hiddenInput.value = selectedIds.join(',');
  });
});
</script>