sample/config/routes.rb
Rails.application.routes.draw do
  get 'index_kno/index'
  get 'index_kno/result'

  root 'home#top'
  
  get 'index_inc/incidents'
  get 'index_inc/new'
  get 'index_inc/result'
  
  get 'home/top'
  
  get '/index', to: 'home#index'
  
  get '/search', to: 'home#search'
  # get '/searchsecond', to: 'home#searchsecond'
  
  get 'home/admin'
  
  get 'importcsv/new'
  post 'importcsv/create_big'
  
  post 'importcsv/create_middle'
  
  post 'importcsv/create_small'
  
  # post 'importcsv/create_gyomu'
  
  post 'importcsv/create_small_security'
  
  post 'importcsv/create_security'
  
  ## 追加部分
  post 'importcsv/create_incident_security'
  
  post 'importcsv/create_incident'
  
  ## 追加部分2
  post 'importcsv/create_category'
  
  ## 追加部分2
  post 'importcsv/create_sakuin'
  post 'importcsv/create_knowledge'
  
  ## 追加部分3
  post 'importcsv/create_incident_category'
  
  ## 追加部分3
  post 'importcsv/create_incident_knowledge'
  
  delete 'importcsv/delete_and_reset_big'
  delete 'importcsv/delete_and_reset_middle'
  delete 'importcsv/delete_and_reset_small'
  # delete 'importcsv/delete_and_reset_gyomu'
  delete 'importcsv/delete_and_reset_small_security'
  delete 'importcsv/delete_and_reset_security'
  
  ## 追加部分
  delete 'importcsv/delete_and_reset_incident_security'
  delete 'importcsv/delete_and_reset_incident'
  
  ## 追加部分2
  delete 'importcsv/delete_and_reset_category'
  
  ## 追加部分2
  delete 'importcsv/delete_and_reset_sakuin'
  delete 'importcsv/delete_and_reset_knowledge'
  
  ## 追加部分3
  delete 'importcsv/delete_and_reset_incident_category'
  
  ## 追加部分3
  delete 'importcsv/delete_and_reset_incident_knowledge'

  ## For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

sample/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

sample/app/models/big.rb
class Big < ApplicationRecord
    has_many :middles
end

sample/app/models/category.rb
## 新規追加ファイル
class Category < ApplicationRecord
    has_many :incident_categories
    has_many :incidents, through: :incident_categories
end

sample/app/models/gyomu.rb
class Gyomu < ApplicationRecord
  belongs_to :small
  has_many :gyomu_securities
  has_many :securities, through: :gyomu_securities
end

sample/app/models/incident.bkup.rb
## 新規追加ファイル
class Incident < ApplicationRecord
    has_many :incident_securities
    has_many :securities, through: :incident_securities
end

sample/app/models/incident.rb
## 新規追加ファイル
class Incident < ApplicationRecord
    has_many :incident_categories
    has_many :categories, through: :incident_categories
    has_many :incident_securities
    has_many :securities, through: :incident_securities
    has_many :incident_knowledges
    has_many :knowledges, through: :incident_knowledges
end

sample/app/models/incident_category.rb
class IncidentCategory < ApplicationRecord
    belongs_to :incident
    belongs_to :category
end

sample/app/models/incident_knowledge.rb
class IncidentKnowledge < ApplicationRecord
    belongs_to :incident
    belongs_to :knowledge
end

sample/app/models/incident_security.rb
## 新規追加ファイル
class IncidentSecurity < ApplicationRecord
  belongs_to :incident
  belongs_to :security
end

sample/app/models/knowledge.rb
class Knowledge < ApplicationRecord
    belongs_to :sakuin
    has_many :incident_knowledges
    has_many :incidents, through: :incident_knowledges
end

sample/app/models/middle.rb
class Middle < ApplicationRecord
  belongs_to :big
  has_many :smalls
end

sample/app/models/sakuin.rb
class Sakuin < ApplicationRecord
    has_many :knowledges
end

sample/app/models/security.bkup.rb
class Security < ApplicationRecord
    has_many :small_securities
    has_many :smalls, through: :small_securities
end

sample/app/models/security.rb
class Security < ApplicationRecord
    has_many :small_securities
    has_many :smalls, through: :small_securities
## 追加箇所
##  belongs_to :small, through: :small_securities
    has_many :incident_securities
    has_many :incidents, through: :incident_securities
end

sample/app/models/small.rb
class Small < ApplicationRecord
  belongs_to :middle
  has_many :small_securities
  has_many :securities, through: :small_securities
end

sample/app/models/small_security.rb
class SmallSecurity < ApplicationRecord
  belongs_to :small
  belongs_to :security
end

sample/app/controllers/home_controller.rb
class HomeController < ApplicationController
protect_from_forgery with: :exception
http_basic_authenticate_with name: "sotupuro", password: "sotupuroPassw0rd!"

  def index
    # DBからすべての「Big」レコードを取得し、それと紐づく「Middles」「Smalls」を取得
    @bigs = Big.all.includes(middles: :smalls)
    ## DBからすべての「Category」レコードを取得し、それと紐づく「Incident」を取得
    ## @categories = Category.all.includes(:incident)
  end
  
  def top
  end

  def search
    # 「small_ids」に指定されたIDに一致する「Smalls」レコードをDBから取得
    @smalls = Small.includes(:securities).where(id: params[:small_ids])
    ##「security_ids」に指定されたIDに一致する「Securities」レコードをDBから取得
    @securities = Security.includes(:incidents)
  end
  
  # def searchsecond
  #   @gyomu_memos = Gyomu.where(id: params[:gyomu_ids]).pluck(:memo)
  #   @securities = Security.includes(:gyomus).where(gyomus: { id: params[:gyomu_ids] })
  # end

  def admin
  end
end

sample/app/helpers/home_helper.rb
module HomeHelper
end

sample/app/helpers/importcsv_helper.rb
module ImportcsvHelper
end

sample/app/helpers/index_inc_helper.rb
module IndexIncHelper
end

sample/app/helpers/index_kno_helper.rb
module IndexKnoHelper
end

sample/app/helpers/search_helper.rb
module SearchHelper
end

sample/app/views/home/admin.html.bkup.erb
<h1>Home#admin</h1>
<p>Find me in app/views/home/admin.html.erb</p>

sample/app/views/home/admin.html.erb
<h1>Home#admin</h1>
<p>Find me in app/views/home/admin.html.erb</p>

sample/app/views/home/index.html.erb
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.83.1">
  <title>Sidebars · Bootstrap v5.0</title>

  <link rel="canonical" href="https://getbootstrap.jp/docs/5.0/examples/sidebars/">

  <!-- Bootstrap core CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <!-- Favicons -->
  <link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
  <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
  <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
  <link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
  <link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
  <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
  <meta name="theme-color" content="#7952b3">
  
  <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
  </style>

    
  <!-- Custom styles for this template -->
  <link href="sidebars.css" rel="stylesheet">
</head>

<div class="title-box">
  <div style="text-align:center", class='font_test'>
    <h1><p class="moji-color"><b>PlusSEC</b></p></h1>
  </div>
</div>

<div style="text-align:right">
  <p>※ブラウザの「戻る」「進む」ボタンを押さないでください</p>
</div>

<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                    <span class="fs-5 d-none d-sm-inline">Menu</span>
                </a>
                <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                    <li>
                        <a href="/index" class="nav-link px-0 align-middle">
                            <i class="fs-4 bi-speedometer2"></i> <span class="ms-1 d-none d-sm-inline">業務から検索</span> </a>
                    </li>
                    <li>
                        <a href="/index_inc/incidents" class="nav-link px-0 align-middle">
                            <i class="fs-4 bi-table"></i> <span class="ms-1 d-none d-sm-inline">事故事例から検索</span></a>
                    </li>
                    <li>
                        <a href="/index_kno/index" class="nav-link px-0 align-middle">
                            <i class="fs-4 bi-table"></i> <span class="ms-1 d-none d-sm-inline">セキュリティ知識</span></a>
                    </li>
                    <li>
                        <!-- /home/topへ -->
                        <a href="/home/top" class="nav-link align-middle px-0">
                            <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">ホームへ</span>
                        </a>
                    </li>
                    
                    <!-- 参考で残してる -->
                    <!--
                    <li>
                        <a href="#submenu3" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                            <i class="fs-4 bi-grid"></i> <span class="ms-1 d-none d-sm-inline">参考</span> </a>
                            <ul class="collapse nav flex-column ms-1" id="submenu3" data-bs-parent="#menu">
                            <li class="w-100">
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">参考</span> 1</a>
                            </li>
                            <li>
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">参考</span> 2</a>
                            </li>
                        </ul>
                    </li>
                    -->
                    
                </ul>
                <hr>
            </div>
        </div>

        <!--searchページに飛ばす-->
          <%= form_tag(search_path, method: "get") do %>
          
              <!--大項目をループで繰り返し表示-->
              <% @bigs.first(2).each do |big| %>
                <div class="p-2 flex-grow-1 bd-highlight">
                    <div class="big">
                      <h2><%= big.memo %></h2>
                      <!--中項目をループで繰り返し表示-->
                      <% big.middles.each do |middle| %>
                        
                        <div class="middle" >
                          <!--中項目のチェックボックスを表示-->
                          <h5>
                            &nbsp;&nbsp;&nbsp;<%= middle.memo %>
                          </h5>
                          <!--全選択-->
                          <!--<input type="checkbox" id="check_all">全て選択
                          
                          <!--小項目をループで繰り返し表示-->
                          <% middle.smalls.each do |small| %>
                            <div class="px-4 flex-grow-1 bd-highlight">
                              <div class="small">
                                <!--小項目のチェックボックスとラベル表示-->
                                <label>
                                  &nbsp;&nbsp;
                                  <%= check_box_tag 'small_ids[]', small.id %>
                                  <%= small.memo %>
                                </label>
                              </div>
                            </div>
                          <% end %>
                        </div>
                      <% end %>
                    </div>
                    </div>
              <% end %>
          
              <!--大項目をループで繰り返し表示-->
                <% @bigs.last(2).each do |big| %>
                  <div class="p-2 flex-grow-1 bd-highlight">
                    <div class="big">
                      <h2><%= big.memo %></h2>
                      <!--中項目をループで繰り返し表示-->
                      <% big.middles.each do |middle| %>
                        
                        <div class="middle" >
                          <!--中項目のチェックボックスを表示-->
                          <h5>
                            &nbsp;&nbsp;&nbsp;<%= middle.memo %>
                          </h5>
                          <!--全選択-->
                          <!--<input type="checkbox" id="check_all">全て選択
                          
                          <!--小項目をループで繰り返し表示-->
                          <% middle.smalls.each do |small| %>
                            <div class="px-4 flex-grow-1 bd-highlight">
                              <div class="small">
                                <!--小項目のチェックボックスとラベル表示-->
                                <label>
                                  &nbsp;&nbsp;
                                  <%= check_box_tag 'small_ids[]', small.id %>
                                  <%= small.memo %>
                                </label>
                              </div>
                            </div>
                          <% end %>
                        </div>
                      <% end %>
                    </div>
                    </div>
                <% end %>
            
            <!--<%= submit_tag('業務検索', class: 'btn btn-outline-primary') %>-->
            <%= submit_tag('検索', class: 'btn-outline-primary fixed_btn') %>
          
          <% end %>

    </div>
</div>

<!-- scriptゾーン -->
<!-- 選択された要素を格納するscript -->
<script>
document.addEventListener('DOMContentLoaded', function() {
  // フォーム要素を取得
  const form = document.getElementById('search-form');
  // チェックボックス要素を取得
  const checkboxes = form.querySelectorAll('input[type=checkbox]');
  // hidden要素を生成
  const hiddenInput = document.createElement('input');
  // hidden要素のタイプを指定
  hiddenInput.type = 'hidden';
  // hidden要素のname属性を指定
  hiddenInput.name = 'small_ids';
  // hidden要素をフォームに追加
  form.appendChild(hiddenInput);
  
  // フォームの送信時に実行する処理
  form.addEventListener('submit', function(event) {
    // チェックが入っているcheckbox要素のみを選択
    const selectedCheckboxes = Array.from(checkboxes).filter(checkbox => checkbox.checked);
    // 選択されたcheckbox要素のvalueを抽出して配列にする
    const selectedIds = selectedCheckboxes.map(checkbox => checkbox.value);
    // hidden要素のvalueに選択されたcheckbox要素のvalueをカンマ区切りで格納する
    hiddenInput.value = selectedIds.join(',');
  });
});
</script>

<script>
  //「全て選択」のチェックボックス
  let checkAll = document.getElementById("checkAll");
  //「全て選択」以外のチェックボックス
  let el = document.getElementsByClassName("checks");
  //全てのチェックボックスをON/OFFする
  const funcCheckAll = (bool) => {
      for (let i = 0; i < el.length; i++) {
          el[i].checked = bool;
      }
  }
  //「checks」のclassを持つ要素のチェック状態で「全て選択」のチェック状態をON/OFFする
  const funcCheck = () => {
      let count = 0;
      for (let i = 0; i < el.length; i++) {
          if (el[i].checked) {
              count += 1;
          }
      }
  
      if (el.length === count) {
          checkAll.checked = true;
      } else {
          checkAll.checked = false;
      }
  };
  //「全て選択」のチェックボックスをクリックした時
  checkAll.addEventListener("click",() => {
      funcCheckAll(checkAll.checked);
  },false);
  
  //「全て選択」以外のチェックボックスをクリックした時
  for (let i = 0; i < el.length; i++) {
      el[i].addEventListener("click", funcCheck, false);
  }
</script>

<script>
  function toggleCheckboxes() {
    var checkboxes = document.querySelectorAll('input[type="checkbox"]');
    var selectAllCheckbox = document.getElementById('selectAll');
    for (var i = 0; i < checkboxes.length; i++) {
      checkboxes[i].checked = selectAllCheckbox.checked;
    }
  }
</script>

sample/app/views/home/search.html.bkup.erb
    <div class="container mx+1">
    <header class="d-flex flex-wrap flex-row ">
      <ul class="nav nav-pills">
        <li class="nav-item">
          <%= form_tag(home_top_path, method: "get") do %>
          <%= submit_tag('ホーム', class: 'btn btn-outline-primary mx+5') %>
          <% end %>
        </li>
      </ul>
    </header>
    <br>
    <button type="button" class="btn btn-primary">業務内容/経験</button>
    <!--<button type="button" class="btn btn-outline-primary">過去事例</button>-->
    <div class="card flex-md-row mx-0 border-primary">
    <div class="container">
    
    
    <!--@smalls（indexページで「small_ids」に指定されたIDに一致するsmallテーブルのすべてのデータ）を順に取り出して繰り返し処理をする-->
    <% @smalls.each do |small| %>
    　<div class="p-2 flex-grow-1 bd-highlight">
    　<div class="row">
        <div class="col-lg-9">
          <div class="card flex-md-row mb-4 border-primary mb-3">
        <!-- テーブルsmall内のmemoカラムの内容を表示 -->
            <h4>選択した業務:　<%= small.memo %></h4>
        　</div>
        </div>
    　</div>
    　</div>
    　
    　
        
        <div class="row">
            <div class="col-6 col-sm-4">
            <h6>考慮するべきセキュリティ事項</h6>
                  <div class="card flex-md-row mb-4 border-primary mb-3 h-md-250">
                    <div class="card-body d-flex flex-column align-items-start ">
                    <!-- テーブルsecurityの関連するデータを取り出して繰り返し処理をする -->
                    <% small.securities.each do |security| %>
                    <!-- テーブルsecurity内のidカラムの内容を表示 -->
                    <p>Security ID: <%= security.id %></p>
                    <!-- テーブルsecurity内のmemoカラムの内容を表示 -->
                    <p>Security memo: <%= security.memo %></p>
                    <% end %>
                    </div>
        　        </div>
            </div>
        　
        　
            <div class="col-6 col-sm-4">
            <h6>過去のインシデント事例</h6>
                    <div class="card flex-md-row mb-4 border-primary mb-3 h-md-250">
                        <div class="card-body d-flex flex-column align-items-start">
                         <!--インシデント事例、DB作成してから対応する-->
                        <!--<% small.securities.each do |security| %>-->
                        <!--<p>Security ID: <%= security.id %></p>-->
                        <!--<% end %>-->
                        </div>
                    </div>
            </div>
            
        
        
        <!--カラム名登録ミスってるので要修正: ditail → detail-->
        <div class="w-100 d-none d-md-block">
            <div class="col-6 col-sm-4">
            <h6>その詳細</h6>
                    <div class="card flex-md-row mb-4 border-primary mb-3 h-md-250">
                        <div class="card-body d-flex flex-column align-items-start">
                        <% small.securities.each do |security| %>
                        <p>Security Detail: <%= security.ditail %></p>
                        <% end %>
                        </div>
                    </div>
            </div>
        </div>
        
    <hr>
        </div>
    <% end %>

</div>
</div>

sample/app/views/home/searchsecond.html.erb
<div class="p-2 flex-grow-1 bd-highlight">
   <div class="card">
      <div style="background-color:#EDF7FF;">
      <p>Gyomu memo:
      <% @gyomu_memos.each do |gyomu_memo| %>
      <%= gyomu_memo %>
      <% end %></p>
      </div>
   </div>
</div>


<div class="p-2 flex-grow-1 bd-highlight">
      <div class="card">
<% @securities.each do |security| %>
      <!--<p><%= security.id %></p>-->
      <p>Security Memo: <%= security.memo %></p>
<% end %>
</div>
  </div>

sample/app/views/home/top.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">
        <div class='font_test'>
          <h1><b>PlusSEC</b></h1>
        </div>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!--管理画面ボタン-->
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0"></ul>
          <%= form_tag(importcsv_new_path, method: "get") do %>
          <%= submit_tag('管理画面', class: 'nav-link') %>
          <% end %>
      </div>
    </div>
  </nav>
  
</br></br></br>
  
<!--灰色の部分-->
<div class="main-container">
  <style>
    #myCarousel.carousel {
      height: 300px; /* 適切な高さを指定してください */
    }
  </style>
  
  
  <div id="myCarousel" class="carousel slide" data-bs-ride="carousel" >
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="3" aria-label="Slide 4"></button>
    </div>
    <div class="carousel-inner">
      
      <div class="carousel-item active">
        <svg class="bd-placeholder-img" width="100%" height="300px" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="300px" fill="#777"></rect></svg>

        <div class="container">
          <div class="carousel-caption text-start">
            <h1>プラスセキュリティ人材とは</h1>
            <p>
            セキュリティの専門家ではないが、日々の業務の中でセキュリティを意識して必要で十分なセキュリティ対策を行える人材のこと。</br>
            具体的には、次に例示するような人材が当てはまります。</br>
            ●新規事業戦略立案時にサイバー関連の脅威への対策を検討する事業部の企画担当者</br>
            ●自社の DX 展開におけるサイバーセキュリティ上のリスクアセスメントを行う、DX 推進部門担当者</br>
            ●自社向けアプリケーション開発において脆弱性が作り込まれないように、セキュアコーディングに関するガイドラインを遵守する開発担当者</br>
            ●システム管理の一環としてアクセスログの異常確認を行う運用担当者</br>
            ●工場の OT システムの保安対策の一環としてサイバー攻撃対策を検討する設備担当者</br>
            </p>
          </div>
        </div>
      </div>
      
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="300px" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="300px" fill="#777"></rect></svg>

        <div class="container">
          <div class="carousel-caption text-start">
            <h1>プラスセキュリティ人材の必要性</h1>
            <p>ITの利活用が急速に進展しており、セキュリティの専門家が不足しているため、専門家一人だけでは全ての業務のセキュリティを確保することが困難です。</br>
            そのため、各人がセキュリティを意識し、対応できる知識が必要です。</br>
            プラスセキュリティ人材の育成は、企業全体のセキュリティレベルを向上させるために重要です。</br>
            プラスセキュリティ人材が一人でも増えれば、サイバー攻撃のリスクを軽減することができます。</br>
            このツールは業務毎に考慮しなければならないポイント、セキュリティを疎かにした場合の事例をセットで学ぶ事ができます。</br>
            セキュリティの考慮事項を考える際の最初の足掛かりとしてご活用ください。</p>
          </div>
        </div>
      </div>
      
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="300px" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="300px" fill="#777"></rect></svg>

        <div class="container">
          <div class="carousel-caption text-start font_example">
            <h1>活用タイミング</h1>
            <p>其ノ壱.システム開発前の要件定義の内容検討中、運用方法検討中</br>
            其ノ弐.データ管理の際情報漏洩を防ぐ為の設計</br>
            其ノ参.構築したシステムのテスト時</br>
            其ノ肆.クレジットカード情報などの機密情報を扱う際</br>
            其ノ伍.従業員の個人情報を扱う際</br>
            其ノ陸.後輩指導時</br>
            其ノ漆.日々の勉強の一助として</p>
          </div>
        </div>
      </div>
      
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="300px" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="300px" fill="#777"></rect></svg>

        <div class="container">
          <div class="carousel-caption">
            <h1>情報引用元</h1>
            <p>・情報システムにおける セキュリティ コントロール ガイドライン Ver.1.0　Software ISAC</br>
               ・政府情報システムにおける セキュリティ・バイ・デザインガイドライン　デジタル庁</p>
            </br></br>
          </div>
        </div>
      </div>
      
    </div>
    <!--前に行くボタン-->
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <!--後に行くボタン-->
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

  <!--下の画像押す部分-->
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
            <div class="hover"> <!--hover用-->
              <%= link_to image_tag("/gyomu.png", style: "max-width: 100%;"), '/index', class: "shu" %>
            </div>
            <div class="card-body">
              <p class="card-text">業務内容から考慮するべきセキュリティ事項を検索</p>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
            <div class="hover"> <!--hover用-->
              <%= link_to image_tag("/jirei2.png", style: "max-width: 100%;"), '/index_inc/incidents', class: "shu" %>
            </div>
            <div class="card-body">
              <p class="card-text">事故事例から考慮するべきセキュリティ事項を検索</p>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
            <div class="hover"> <!--hover用-->
              <%= link_to image_tag("/text.png", style: "max-width: 100%;"), '/index_kno/index', class: "shu" %>
            </div>
            <div class="card-body">
              <p class="card-text">本Webサイトで出てくる単語について検索可能</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  </div>
</div>


  <!-- 
  <header class="d-flex flex-wrap flex-row-reverse py-3 mb-4 ">
    <ul class="nav nav-pills">
      <li class="nav-item">
        <%= form_tag(importcsv_new_path, method: "get") do %>
        <%= submit_tag('管理画面', class: 'nav-link') %>
        <% end %>
      </li>
    </ul>
  </header>
  -->


  <!--
  <%= form_tag('/index', method: "get") do %>
  <%= submit_tag('業務内容/経験から探す', class: 'btn btn-outline-primary') %>
  <% end %>
  
  <%= form_tag('/index_inc/incidents', method: "get") do %>
  <%= submit_tag('事故事例から探す', class: 'btn btn-outline-primary') %>
  <% end %>
  
  <%= form_tag('/index_kno/index', method: "get") do %>
  <%= submit_tag('セキュリティ単語', class: 'btn btn-outline-primary') %>
  <% end %>
  -->