sample/config/routes.rb
Rails.application.routes.draw do
  get 'index_kno/index'
  get 'index_kno/result'

  root 'home#top'
  
  get 'index_inc/incidents'
  get 'index_inc/new'
  get 'index_inc/result'
  
  get 'home/top'
  
  get '/index', to: 'home#index'
  
  get '/search', to: 'home#search'
  # get '/searchsecond', to: 'home#searchsecond'
  
  get 'home/admin'
  
  get 'importcsv/new'
  post 'importcsv/create_big'
  
  post 'importcsv/create_middle'
  
  post 'importcsv/create_small'
  
  # post 'importcsv/create_gyomu'
  
  post 'importcsv/create_small_security'
  
  post 'importcsv/create_security'
  
  ## 追加部分
  post 'importcsv/create_incident_security'
  
  post 'importcsv/create_incident'
  
  ## 追加部分2
  post 'importcsv/create_category'
  
  ## 追加部分2
  post 'importcsv/create_sakuin'
  post 'importcsv/create_knowledge'
  
  ## 追加部分3
  post 'importcsv/create_incident_category'
  
  ## 追加部分3
  post 'importcsv/create_incident_knowledge'
  
  delete 'importcsv/delete_and_reset_big'
  delete 'importcsv/delete_and_reset_middle'
  delete 'importcsv/delete_and_reset_small'
  # delete 'importcsv/delete_and_reset_gyomu'
  delete 'importcsv/delete_and_reset_small_security'
  delete 'importcsv/delete_and_reset_security'
  
  ## 追加部分
  delete 'importcsv/delete_and_reset_incident_security'
  delete 'importcsv/delete_and_reset_incident'
  
  ## 追加部分2
  delete 'importcsv/delete_and_reset_category'
  
  ## 追加部分2
  delete 'importcsv/delete_and_reset_sakuin'
  delete 'importcsv/delete_and_reset_knowledge'
  
  ## 追加部分3
  delete 'importcsv/delete_and_reset_incident_category'
  
  ## 追加部分3
  delete 'importcsv/delete_and_reset_incident_knowledge'

  ## For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

sample/app/controllers/importcsv_controller.rb
class ImportcsvController < ApplicationController
protect_from_forgery with: :exception
http_basic_authenticate_with name: "Plus_master", password: "Kamei_B@NZ@!"

require 'csv'

  def new
  end

  def create_big 
    file = params[:file]
    CSV.foreach(file.path, headers: true, encoding: 'Shift_JIS:UTF-8') do |row|
      model_instance = Big.new
      model_instance.id = row['id']
      model_instance.memo = row['memo']
      model_instance.save!
    end
    redirect_to importcsv_new_path, notice: 'CSVをインポートしました。'
  end
  
  def delete_and_reset_big
    Big.delete_all
    ActiveRecord::Base.connection.reset_sequence!('bigs', 'id')
    redirect_to importcsv_new_path, notice: 'レコードを全削除し、IDをリセットしました。'
  end
  
  def create_middle 
    file = params[:file]
    CSV.foreach(file.path, headers: true, encoding: 'Shift_JIS:UTF-8') do |row|
      model_instance = Middle.new
      model_instance.id = row['id']
      model_instance.big_id = row['big_id']
      model_instance.memo = row['memo']
      model_instance.save!
    end
    redirect_to importcsv_new_path, notice: 'CSVをインポートしました。'
  end
  
  def delete_and_reset_middle
    Middle.delete_all
    ActiveRecord::Base.connection.reset_sequence!('middles', 'id')
    redirect_to importcsv_new_path, notice: 'レコードを全削除し、IDをリセットしました。'
  end

    
  def create_small
    file = params[:file]
    CSV.foreach(file.path, headers: true, encoding: 'Shift_JIS:UTF-8') do |row|
      model_instance = Small.new
      model_instance.id = row['id']
      model_instance.middle_id = row['middle_id']
      model_instance.memo = row['memo']
      model_instance.save!
    end
    redirect_to importcsv_new_path, notice: 'CSVをインポートしました。'
  end
  
  def delete_and_reset_small
    Small.delete_all
    ActiveRecord::Base.connection.reset_sequence!('smalls', 'id')
    redirect_to importcsv_new_path, notice: 'レコードを全削除し、IDをリセットしました。'
  end
  
  # def create_gyomu
  #   file = params[:file]
  #   CSV.foreach(file.path, headers: true, encoding: 'Shift_JIS:UTF-8') do |row|
  #     model_instance = Gyomu.new
  #     model_instance.id = row['id']
  #     model_instance.small_id = row['small_id']
  #     model_instance.memo = row['memo']
  #     model_instance.save!
  #   end
  #   redirect_to importcsv_new_path, notice: 'CSVをインポートしました。'
  # end
  
  # def delete_and_reset_gyomu
  #   Gyomu.delete_all
  #   ActiveRecord::Base.connection.reset_sequence!('gyomus', 'id')
  #   redirect_to importcsv_new_path, notice: 'レコードを全削除し、IDをリセットしました。'
  # end
  
  def create_small_security
    file = params[:file]
    CSV.foreach(file.path, headers: true) do |row|
      model_instance = SmallSecurity.new
      model_instance.id = row['id']
      model_instance.small_id = row['small_id']
      model_instance.security_id = row['security_id']
      model_instance.save!
    end
    redirect_to importcsv_new_path, notice: 'CSVをインポートしました。'
  end
  
  def delete_and_reset_small_security
    SmallSecurity.delete_all
    ActiveRecord::Base.connection.reset_sequence!('small_securitys', 'id')
    redirect_to importcsv_new_path, notice: 'レコードを全削除し、IDをリセットしました。'
  end
  
  def create_security
    file = params[:file]
    CSV.foreach(file.path, headers: true, encoding: 'Shift_JIS:UTF-8') do |row|
      model_instance = Security.new
      model_instance.id = row['id']
      model_instance.memo = row['memo']
      model_instance.ditail = row['ditail']
      model_instance.save!
    end
    redirect_to importcsv_new_path, notice: 'CSVをインポートしました。'
  end
  
  def delete_and_reset_security
    Security.delete_all
    ActiveRecord::Base.connection.reset_sequence!('securitys', 'id')
    redirect_to importcsv_new_path, notice: 'レコードを全削除し、IDをリセットしました。'
  end
  
#   def create_big 
#     file = params[:file]
#     CSV.foreach(file.path, headers: true) do |row|
#       model_instance = Big.new
#       model_instance.memo = row['attribute1']
#       model_instance.save!
#     end
#     redirect_to new_admin_import_csv_path, notice: 'CSVをインポートしました。'
#   end


  
## Incidentカラムを追加
  def create_incident
    file = params[:file]
    CSV.foreach(file.path, headers: true, encoding: 'Shift_JIS:UTF-8') do |row|
      model_instance = Incident.new
      model_instance.id = row['id']
      model_instance.date = row['date']
      model_instance.summary = row['summary']
      model_instance.cause = row['cause']
      model_instance.effect = row['effect']
      model_instance.taisaku = row['taisaku']
      model_instance.url = row['url']
      model_instance.save!
    end
    redirect_to importcsv_new_path, notice: 'CSVをインポートしました。'
  end
  
  def delete_and_reset_incident
    Incident.delete_all
    ActiveRecord::Base.connection.reset_sequence!('incidents', 'id')
    redirect_to importcsv_new_path, notice: 'レコードを全削除し、IDをリセットしました。'
  end

## incident_securityカラムを追加
  def create_incident_security
    file = params[:file]
    CSV.foreach(file.path, headers: true) do |row|
      model_instance = IncidentSecurity.new
      model_instance.id = row['id']
      model_instance.incident_id = row['incident_id']
      model_instance.security_id = row['security_id']
      model_instance.save!
    end
    redirect_to importcsv_new_path, notice: 'CSVをインポートしました。'
  end
  
  def delete_and_reset_incident_security
    IncidentSecurity.delete_all
    ActiveRecord::Base.connection.reset_sequence!('incident_securities', 'id')
    redirect_to importcsv_new_path, notice: 'レコードを全削除し、IDをリセットしました。'
  end

  ## Category追加
  def create_category 
    file = params[:file]
    CSV.foreach(file.path, headers: true, encoding: 'Shift_JIS:UTF-8') do |row|
      model_instance = Category.new
      model_instance.id = row['id']
      model_instance.memo = row['memo']
      model_instance.save!
    end
    redirect_to importcsv_new_path, notice: 'CSVをインポートしました。'
  end
  
  def delete_and_reset_category
    Category.delete_all
    ActiveRecord::Base.connection.reset_sequence!('categories', 'id')
    redirect_to importcsv_new_path, notice: 'レコードを全削除し、IDをリセットしました。'
  end
  
  ## Sakuin追加
  def create_sakuin
    file = params[:file]
    CSV.foreach(file.path, headers: true, encoding: 'Shift_JIS:UTF-8') do |row|
      model_instance = Sakuin.new
      model_instance.id = row['id']
      model_instance.memo = row['memo']
      model_instance.save!
    end
    redirect_to importcsv_new_path, notice: 'CSVをインポートしました。'
  end
  
  def delete_and_reset_sakuin
    Sakuin.delete_all
    ActiveRecord::Base.connection.reset_sequence!('sakuins', 'id')
    redirect_to importcsv_new_path, notice: 'レコードを全削除し、IDをリセットしました。'
  end
  
  ## Knowledge追加
  def create_knowledge
    file = params[:file]
    CSV.foreach(file.path, headers: true, encoding: 'Shift_JIS:UTF-8') do |row|
      model_instance = Knowledge.new
      model_instance.id = row['id']
      model_instance.word = row['word']
      model_instance.memo = row['memo']
      model_instance.url = row['url']
      model_instance.sakuin_id = row['sakuin_id']
      model_instance.save!
    end
    redirect_to importcsv_new_path, notice: 'CSVをインポートしました。'
  end
  
  def delete_and_reset_knowledge
    Knowledge.delete_all
    ActiveRecord::Base.connection.reset_sequence!('knowledges', 'id')
    redirect_to importcsv_new_path, notice: 'レコードを全削除し、IDをリセットしました。'
  end
  
  def create_incident_category
    file = params[:file]
    CSV.foreach(file.path, headers: true) do |row|
      model_instance = IncidentCategory.new
      model_instance.id = row['id']
      model_instance.incident_id = row['incident_id']
      model_instance.category_id = row['category_id']
      model_instance.save!
    end
    redirect_to importcsv_new_path, notice: 'CSVをインポートしました。'
  end
  
  def delete_and_reset_incident_category
    IncidentCategory.delete_all
    ActiveRecord::Base.connection.reset_sequence!('incident_categorys', 'id')
    redirect_to importcsv_new_path, notice: 'レコードを全削除し、IDをリセットしました。'
  end
  
  def create_incident_knowledge
    file = params[:file]
    CSV.foreach(file.path, headers: true) do |row|
      model_instance = IncidentKnowledge.new
      model_instance.id = row['id']
      model_instance.knowledge_id = row['knowledge_id']
      model_instance.incident_id = row['incident_id']
      model_instance.save!
    end
    redirect_to importcsv_new_path, notice: 'CSVをインポートしました。'
  end
  
  def delete_and_reset_incident_knowledge
    IncidentKnowledge.delete_all
    ActiveRecord::Base.connection.reset_sequence!('incident_knowledges', 'id')
    redirect_to importcsv_new_path, notice: 'レコードを全削除し、IDをリセットしました。'
  end
end

sample/app/helpers/importcsv_helper.rb
module ImportcsvHelper
end

sample/app/views/importcsv/new.html.bkup2.erb
<header class="d-flex flex-wrap flex-row ">
  <ul class="nav nav-pills">
    <li class="nav-item">
      <%= form_tag(home_top_path, method: "get") do %>
      <%= submit_tag('ホーム', class: 'btn btn-outline-primary mx+5') %>
      <% end %>
    </li>
  </ul>
</header>

<h2>インポート手順</h2>
<h6>
１.「レコード全削除 & IDリセット」を実施<br>
２.「ファイル選択」を押してインポートしたいCSVファイルを選択<br>
３.「インポート」ボタンを押下<br>
※インポート順はBig⇒Middle⇒Small⇒Security⇒Incident⇒Small_Security⇒Incident⇒Security</h6>

<br></br>

<h1>Big CSVインポート</h1>
<%= form_tag(importcsv_create_big_path, method: :post, multipart: true) do %>
  <div class="form-group">
    <%= label_tag(:file, 'CSVファイルを選択') %>
    <%= file_field_tag(:file, accept: '.csv', required: true, class: 'form-control-file') %>
  </div>
  <%= submit_tag('インポート', class: 'btn btn-outline-primary') %>
<% end %>


<%= button_to 'レコード全削除 & IDリセット', importcsv_delete_and_reset_big_path, method: :delete, data: { confirm: 'レコードを全削除し、IDをリセットしてもよろしいですか？' }, class: 'btn btn-outline-danger' %>

<br></br><br></br>

<h1>Middle CSVインポート</h1>

<%= form_tag(importcsv_create_middle_path, method: :post, multipart: true) do %>
  <div class="form-group">
    <%= label_tag(:file, 'CSVファイルを選択') %>
    <%= file_field_tag(:file, accept: '.csv', required: true, class: 'form-control-file') %>
  </div>
  <%= submit_tag('インポート', class: 'btn btn-outline-primary') %>
<% end %>


<%= button_to 'レコード全削除 & IDリセット', importcsv_delete_and_reset_middle_path, method: :delete, data: { confirm: 'レコードを全削除し、IDをリセットしてもよろしいですか？' }, class: 'btn btn-outline-danger' %>

<br></br><br></br>

<h1>Small CSVインポート</h1>

<%= form_tag(importcsv_create_small_path, method: :post, multipart: true) do %>
  <div class="form-group">
    <%= label_tag(:file, 'CSVファイルを選択') %>
    <%= file_field_tag(:file, accept: '.csv', required: true, class: 'form-control-file') %>
  </div>
  <%= submit_tag('インポート', class: 'btn btn-outline-primary') %>
<% end %>


<%= button_to 'レコード全削除 & IDリセット', importcsv_delete_and_reset_small_path, method: :delete, data: { confirm: 'レコードを全削除し、IDをリセットしてもよろしいですか？' }, class: 'btn btn-outline-danger' %>

<br></br><br></br>

<h1>Small_security CSVインポート</h1>

<%= form_tag(importcsv_create_small_security_path, method: :post, multipart: true) do %>
  <div class="form-group">
    <%= label_tag(:file, 'CSVファイルを選択') %>
    <%= file_field_tag(:file, accept: '.csv', required: true, class: 'form-control-file') %>
  </div>
  <%= submit_tag('インポート', class: 'btn btn-outline-primary') %>
<% end %>


<%= button_to 'レコード全削除 & IDリセット', importcsv_delete_and_reset_small_security_path, method: :delete, data: { confirm: 'レコードを全削除し、IDをリセットしてもよろしいですか？' }, class: 'btn btn-outline-danger' %>

<br></br><br></br>

<h1>Security CSVインポート</h1>

<%= form_tag(importcsv_create_security_path, method: :post, multipart: true) do %>
  <div class="form-group">
    <%= label_tag(:file, 'CSVファイルを選択') %>
    <%= file_field_tag(:file, accept: '.csv', required: true, class: 'form-control-file') %>
  </div>
  <%= submit_tag('インポート', class: 'btn btn-outline-primary') %>
<% end %>


<%= button_to 'レコード全削除 & IDリセット', importcsv_delete_and_reset_security_path, method: :delete, data: { confirm: 'レコードを全削除し、IDをリセットしてもよろしいですか？' }, class: 'btn btn-outline-danger' %>

<!-- 以下追加部分 -->

<br></br><br></br>

<h1>Incident_security CSVインポート</h1>

<%= form_tag(importcsv_create_incident_security_path, method: :post, multipart: true) do %>
  <div class="form-group">
    <%= label_tag(:file, 'CSVファイルを選択') %>
    <%= file_field_tag(:file, accept: '.csv', required: true, class: 'form-control-file') %>
  </div>
  <%= submit_tag('インポート', class: 'btn btn-outline-primary') %>
<% end %>


<%= button_to 'レコード全削除 & IDリセット', importcsv_delete_and_reset_incident_security_path, method: :delete, data: { confirm: 'レコードを全削除し、IDをリセットしてもよろしいですか？' }, class: 'btn btn-outline-danger' %>

<br></br><br></br>

<h1>Incident CSVインポート</h1>

<%= form_tag(importcsv_create_incident_path, method: :post, multipart: true) do %>
  <div class="form-group">
    <%= label_tag(:file, 'CSVファイルを選択') %>
    <%= file_field_tag(:file, accept: '.csv', required: true, class: 'form-control-file') %>
  </div>
  <%= submit_tag('インポート', class: 'btn btn-outline-primary') %>
<% end %>


<%= button_to 'レコード全削除 & IDリセット', importcsv_delete_and_reset_incident_path, method: :delete, data: { confirm: 'レコードを全削除し、IDをリセットしてもよろしいですか？' }, class: 'btn btn-outline-danger' %>

<br></br><br></br>

sample/app/views/importcsv/new.html.erb
<header class="d-flex flex-wrap flex-row ">
  <ul class="nav nav-pills">
    <li class="nav-item">
      <%= form_tag(home_top_path, method: "get") do %>
      <%= submit_tag('ホーム', class: 'btn btn-outline-primary mx+5') %>
      <% end %>
    </li>
  </ul>
</header>

<h2>インポート手順</h2>
<h6>
１.「レコード全削除 & IDリセット」を実施<br>
２.「ファイル選択」を押してインポートしたいCSVファイルを選択<br>
３.「インポート」ボタンを押下<br>
※インポート順はBig⇒Middle⇒Small⇒Security⇒Incident⇒Small_Security⇒Incident⇒Security</h6>

<br></br>

<h1>Big CSVインポート</h1>
<%= form_tag(importcsv_create_big_path, method: :post, multipart: true) do %>
  <div class="form-group">
    <%= label_tag(:file, 'CSVファイルを選択') %>
    <%= file_field_tag(:file, accept: '.csv', required: true, class: 'form-control-file') %>
  </div>
  <%= submit_tag('インポート', class: 'btn btn-outline-primary') %>
<% end %>


<%= button_to 'レコード全削除 & IDリセット', importcsv_delete_and_reset_big_path, method: :delete, data: { confirm: 'レコードを全削除し、IDをリセットしてもよろしいですか？' }, class: 'btn btn-outline-danger' %>

<br></br><br></br>

<h1>Middle CSVインポート</h1>

<%= form_tag(importcsv_create_middle_path, method: :post, multipart: true) do %>
  <div class="form-group">
    <%= label_tag(:file, 'CSVファイルを選択') %>
    <%= file_field_tag(:file, accept: '.csv', required: true, class: 'form-control-file') %>
  </div>
  <%= submit_tag('インポート', class: 'btn btn-outline-primary') %>
<% end %>


<%= button_to 'レコード全削除 & IDリセット', importcsv_delete_and_reset_middle_path, method: :delete, data: { confirm: 'レコードを全削除し、IDをリセットしてもよろしいですか？' }, class: 'btn btn-outline-danger' %>

<br></br><br></br>

<h1>Small CSVインポート</h1>

<%= form_tag(importcsv_create_small_path, method: :post, multipart: true) do %>
  <div class="form-group">
    <%= label_tag(:file, 'CSVファイルを選択') %>
    <%= file_field_tag(:file, accept: '.csv', required: true, class: 'form-control-file') %>
  </div>
  <%= submit_tag('インポート', class: 'btn btn-outline-primary') %>
<% end %>


<%= button_to 'レコード全削除 & IDリセット', importcsv_delete_and_reset_small_path, method: :delete, data: { confirm: 'レコードを全削除し、IDをリセットしてもよろしいですか？' }, class: 'btn btn-outline-danger' %>

<br></br><br></br>

<h1>Small_security CSVインポート</h1>

<%= form_tag(importcsv_create_small_security_path, method: :post, multipart: true) do %>
  <div class="form-group">
    <%= label_tag(:file, 'CSVファイルを選択') %>
    <%= file_field_tag(:file, accept: '.csv', required: true, class: 'form-control-file') %>
  </div>
  <%= submit_tag('インポート', class: 'btn btn-outline-primary') %>
<% end %>


<%= button_to 'レコード全削除 & IDリセット', importcsv_delete_and_reset_small_security_path, method: :delete, data: { confirm: 'レコードを全削除し、IDをリセットしてもよろしいですか？' }, class: 'btn btn-outline-danger' %>

<br></br><br></br>

<h1>Security CSVインポート</h1>

<%= form_tag(importcsv_create_security_path, method: :post, multipart: true) do %>
  <div class="form-group">
    <%= label_tag(:file, 'CSVファイルを選択') %>
    <%= file_field_tag(:file, accept: '.csv', required: true, class: 'form-control-file') %>
  </div>
  <%= submit_tag('インポート', class: 'btn btn-outline-primary') %>
<% end %>


<%= button_to 'レコード全削除 & IDリセット', importcsv_delete_and_reset_security_path, method: :delete, data: { confirm: 'レコードを全削除し、IDをリセットしてもよろしいですか？' }, class: 'btn btn-outline-danger' %>

<!-- 以下追加部分 -->

<br></br><br></br>

<h1>Incident_security CSVインポート</h1>

<%= form_tag(importcsv_create_incident_security_path, method: :post, multipart: true) do %>
  <div class="form-group">
    <%= label_tag(:file, 'CSVファイルを選択') %>
    <%= file_field_tag(:file, accept: '.csv', required: true, class: 'form-control-file') %>
  </div>
  <%= submit_tag('インポート', class: 'btn btn-outline-primary') %>
<% end %>


<%= button_to 'レコード全削除 & IDリセット', importcsv_delete_and_reset_incident_security_path, method: :delete, data: { confirm: 'レコードを全削除し、IDをリセットしてもよろしいですか？' }, class: 'btn btn-outline-danger' %>

<br></br><br></br>

<h1>Incident CSVインポート</h1>

<%= form_tag(importcsv_create_incident_path, method: :post, multipart: true) do %>
  <div class="form-group">
    <%= label_tag(:file, 'CSVファイルを選択') %>
    <%= file_field_tag(:file, accept: '.csv', required: true, class: 'form-control-file') %>
  </div>
  <%= submit_tag('インポート', class: 'btn btn-outline-primary') %>
<% end %>


<%= button_to 'レコード全削除 & IDリセット', importcsv_delete_and_reset_incident_path, method: :delete, data: { confirm: 'レコードを全削除し、IDをリセットしてもよろしいですか？' }, class: 'btn btn-outline-danger' %>

<br></br><br></br>

<h1>Category CSVインポート</h1>

<%= form_tag(importcsv_create_category_path, method: :post, multipart: true) do %>
  <div class="form-group">
    <%= label_tag(:file, 'CSVファイルを選択') %>
    <%= file_field_tag(:file, accept: '.csv', required: true, class: 'form-control-file') %>
  </div>
  <%= submit_tag('インポート', class: 'btn btn-outline-primary') %>
<% end %>


<%= button_to 'レコード全削除 & IDリセット', importcsv_delete_and_reset_category_path, method: :delete, data: { confirm: 'レコードを全削除し、IDをリセットしてもよろしいですか？' }, class: 'btn btn-outline-danger' %>

<br></br><br></br>

<h1>Sakuin CSVインポート</h1>

<%= form_tag(importcsv_create_sakuin_path, method: :post, multipart: true) do %>
  <div class="form-group">
    <%= label_tag(:file, 'CSVファイルを選択') %>
    <%= file_field_tag(:file, accept: '.csv', required: true, class: 'form-control-file') %>
  </div>
  <%= submit_tag('インポート', class: 'btn btn-outline-primary') %>
<% end %>


<%= button_to 'レコード全削除 & IDリセット', importcsv_delete_and_reset_sakuin_path, method: :delete, data: { confirm: 'レコードを全削除し、IDをリセットしてもよろしいですか？' }, class: 'btn btn-outline-danger' %>

<br></br><br></br>

<h1>Knowledge CSVインポート</h1>

<%= form_tag(importcsv_create_knowledge_path, method: :post, multipart: true) do %>
  <div class="form-group">
    <%= label_tag(:file, 'CSVファイルを選択') %>
    <%= file_field_tag(:file, accept: '.csv', required: true, class: 'form-control-file') %>
  </div>
  <%= submit_tag('インポート', class: 'btn btn-outline-primary') %>
<% end %>


<%= button_to 'レコード全削除 & IDリセット', importcsv_delete_and_reset_knowledge_path, method: :delete, data: { confirm: 'レコードを全削除し、IDをリセットしてもよろしいですか？' }, class: 'btn btn-outline-danger' %>

<br></br><br></br>

<h1>Incident_Category CSVインポート</h1>

<%= form_tag(importcsv_create_incident_category_path, method: :post, multipart: true) do %>
  <div class="form-group">
    <%= label_tag(:file, 'CSVファイルを選択') %>
    <%= file_field_tag(:file, accept: '.csv', required: true, class: 'form-control-file') %>
  </div>
  <%= submit_tag('インポート', class: 'btn btn-outline-primary') %>
<% end %>


<%= button_to 'レコード全削除 & IDリセット', importcsv_delete_and_reset_incident_category_path, method: :delete, data: { confirm: 'レコードを全削除し、IDをリセットしてもよろしいですか？' }, class: 'btn btn-outline-danger' %>

<br></br><br></br>

<h1>Incident_Knowledge CSVインポート</h1>

<%= form_tag(importcsv_create_incident_knowledge_path, method: :post, multipart: true) do %>
  <div class="form-group">
    <%= label_tag(:file, 'CSVファイルを選択') %>
    <%= file_field_tag(:file, accept: '.csv', required: true, class: 'form-control-file') %>
  </div>
  <%= submit_tag('インポート', class: 'btn btn-outline-primary') %>
<% end %>


<%= button_to 'レコード全削除 & IDリセット', importcsv_delete_and_reset_incident_knowledge_path, method: :delete, data: { confirm: 'レコードを全削除し、IDをリセットしてもよろしいですか？' }, class: 'btn btn-outline-danger' %>

<br></br><br></br>